name: docs-build-static-action
description: Build documentation

inputs:
  revision:
    required: true
  src-root:
    default: "./"
  build-root:
    default: "./_docs"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm i @diplodoc/cli -g
      shell: bash

    - name: Build _docs
      id: build-html
      run: |
        set +e
        set -o pipefail

        yfm -i ${{ inputs.src-root }} -o ${{ inputs.build-root }} | tee './build.log'

        echo "exitcode=$?" >> $GITHUB_OUTPUT

      shell: bash

    - name: Save inputs
      run: |
        mkdir -p ./inputs
        echo ${{ inputs.revision }} > ./inputs/revision
        echo ${{ github.event.number }} > ./inputs/pr-number
      shell: bash
    - name: Upload inputs
      uses: actions/upload-artifact@v3
      with:
        name: inputs
        path: inputs/
        retention-days: 1
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-html
        path: ${{ inputs.build-root }}
        retention-days: 1
    - name: Upload build log
      uses: actions/upload-artifact@v3
      with:
        name: build-log-html
        path: ./build.log
        retention-days: 1
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: github-pages
        path: ${{ inputs.build-root }}
        retention-days: 1
    - name: Exit
      run: |
        exitcode=${{ steps.build-html.outputs.exitcode }}

        if [ "$exitcode" -eq 0 ]; then
            echo "Build exited successfully."
        else
          echo "Build exited with an error. Exit code: $exitcode"
          exit $exitcode
        fi
      shell: bash